services:
  - type: web
    name: entree-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --chdir backend
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
